export const InputTypesValues = [
  'button',
  'checkbox',
  'color',
  'date',
  'datetime-local',
  'email',
  'file',
  'hidden',
  'image',
  'month',
  'number',
  'password',
  'radio',
  'range',
  'reset',
  'search',
  'submit',
  'tel',
  'text',
  'submit',
  'time',
  'url',
  'week',
] as const;
export type InputTypes = typeof InputTypesValues[number];